### ISSUE TITLE
First time page autochange

### ISSUE THREAD

**Issue by RogerParis** [hayribakici/infiniteviewpager#1]
Hello,

First of all thanks for your library, works great and helped me create a Calendar :)

I have to say I noticed that first time you run it, you are in page 0, then if you scroll a little bit (right or left it doesn't matter), not enough to be in another page, the instance of the page -1 will  be anyway created and the page 0 will now be the page -1. This bug continues till you open correctly a page like scrolling completely.

I hope you understand where is the problem. But I actually don't know if you will consider this a problem anyway haha.

Keep up with the good job!

Roger.

**Comment by hayribakici** [comment]
Hi Roger,

i am glad it helped you. Yes, this looks like a bug. I will try to fix it next week.

cheers

**Comment by RogerParis** [comment]
Cool thehayro, thanks a lot :)
