### ISSUE TITLE
Issues with adding your library to my android project's build.gradle

### ISSUE THREAD

**Issue by henrykvdb** [hayribakici/infiniteviewpager#10]
I tried to add your library with the follow line I found on [mavenreposetory](https://mvnrepository.com/artifact/com.thehayro/infiniteviewpager/0.4)

which gives me the following gradle error when I build:

    A problem occurred configuring project ':app'.
    > Could not resolve all dependencies for configuration ':app:_debugCompile'.
       > Could not find com.google.android:support-v4:r13.
         Searched in the following locations:
             https://jcenter.bintray.com/com/google/android/support-v4/r13/support-v4-r13.pom
             https://jcenter.bintray.com/com/google/android/support-v4/r13/support-v4-r13.jar
             https://repo1.maven.org/maven2/com/google/android/support-v4/r13/support-v4-r13.pom
             https://repo1.maven.org/maven2/com/google/android/support-v4/r13/support-v4-r13.jar
             file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/support-v4/r13/support-v4-r13.pom
             file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/support-v4/r13/support-v4-r13.jar
             file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/google/m2repository/com/google/android/support-v4/r13/support-v4-r13.pom
             file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/google/m2repository/com/google/android/support-v4/r13/support-v4-r13.jar
         Required by:           
             xkcdexplain:app:unspecified
             xkcdexplain:app:unspecified > com.thehayro:infiniteviewpager:0.4

The support library the error is referring to is ancient and is nowhere to be found on the internet.

Any idea how I can fix this?

**Comment by hayribakici** [comment]
Hey!

Thank you for using the library. I agree the support lib is ancient. I will
update it to the latest version and upload it. If you need the library very
urgently, I recommend to you to build an aar and bind bund it to your
project manually and exclude the dependency of the support library in you
pom.

Best regards

Am 11. Dezember 2016 00:48:25 MEZ, schrieb henrykvdb <
notifications@github.com>:


>
> I tried to add your library with the follow line I found on
mavenreposetory
<https://mvnrepository.com/artifact/com.thehayro/infiniteviewpager/0.4>
>
> which gives me the following gradle error when I build:
>
> A problem occurred configuring project ':app'. > Could not resolve all
dependencies for configuration ':app:_debugCompile'. > Could not find
com.google.android:support-v4:r13. Searched in the following locations:
https://jcenter.bintray.com/com/google/android/support-v4/r13/support-v4-r13.pom
https://jcenter.bintray.com/com/google/android/support-v4/r13/support-v4-r13.jar
https://repo1.maven.org/maven2/com/google/android/support-v4/r13/support-v4-r13.pom
https://repo1.maven.org/maven2/com/google/android/support-v4/r13/support-v4-r13.jar
file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/support-v4/r13/support-v4-r13.pom
file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/android/m2repository/com/google/android/support-v4/r13/support-v4-r13.jar
file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/google/m2repository/com/google/android/support-v4/r13/support-v4-r13.pom
file:/C:/Users/Henrykvdb/AppData/Local/Android/android-sdk/extras/google/m2repository/com/google/android/support-v4/r13/support-v4-r13.jar
Required by: xkcdexplain:app:unspecified xkcdexplain:app:unspecified >
com.thehayro:infiniteviewpager:0.4
>
> The support library the error is referring to is ancient and is nowhere
to be found on the internet.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
<https://github.com/hayribakici/infiniteviewpager/issues/10>, or mute the
thread

**Comment by henrykvdb** [comment]
Thanks for still supporting this old library of yours! It's not too urgent (currently have the classes added in a package) so I'll just wait for you to update it.

Your library works like a champ, only thing that's slightly annoying is that if you scroll fast you'll scroll again before the library is able to put you back on the middle view. This makes the app block as it needs to set you to the middle view again before you can scroll again. Having 5 views would probably solve this issue (if start on page n and you reach the 1st or 5th page (out of the 5 pages) you should be put on page n+2 then though).
Any plans to  fix/improve that part or will I have to live with the app sometimes blocking up a bit?

**Comment by naclcaleb** [comment]
I'm still getting this problem...

**Comment by hayribakici** [comment]
@naclcaleb Hi, could you paste your error message here?
Thanks

**Comment by naclcaleb** [comment]
ERROR: Failed to resolve: com.google.android:support-v4:r13

**Comment by naclcaleb** [comment]
Also, is there any way to make this work for Fragments instead of ViewGroups? It would be nice, but I could do it without them.

**Comment by hayribakici** [comment]
@naclcaleb Okay, thank you. I'll take a look at the error asap.
Regarding your question about Fragments: it is technically possible with this configuration of the `ViewPager`. For me, timewise it would be difficult to implement. Would you like to do it?

**Comment by naclcaleb** [comment]
Thanks @hayribakici, 

I'm not sure. I'd love to, but I need to finish my project as fast as possible, so I think I might just switch to using `ViewGroup`s.

**Comment by hayribakici** [comment]
@naclcaleb I pushed a new version `0.4.4`. You can get it through jitpack:
`implementation 'com.github.hayribakici:infiniteviewpager:0.4.4'`.
Please give me feedback if it worked or not. 

Cheers

**Comment by naclcaleb** [comment]
It says `ERROR: Failed to resolve: com.github.hayribakici:infiniteviewpager:0.4.4`

**Comment by hayribakici** [comment]
This looks like a bigger issue with jitpack.
For now, If you want you can use 
`implementation 'com.github.hayribakici:infiniteviewpager:develop-SNAPSHOT'`
That should work for now. I'll create a separate issue (#12) with jitpack

**Comment by naclcaleb** [comment]
Thanks for the help!

**Comment by hayribakici** [comment]
You're welcome.
Closing issue.
