### ISSUE TITLE
call setCurrentIndicator NullPointer Exception

### ISSUE THREAD

**Issue by germands** [hayribakici/infiniteviewpager#5]
Hi, I've implemented your nice lib, and during the implementation I've found that if you call pager.setCurrentIndicator(int) just after you create the pager, It throws nullpointer exception in the reset() call in InfinitePagerAdapter class, so I've modified the Adapter class with this code:

```
void reset() {
    for (PageModel<T> pageModel : mPageModels) {
       if (pageModel!=null) pageModel.removeAllChildren();
    }
}
```

Maybe it helps others...
thanks!

**Comment by hayribakici** [comment]
do you wanna make a pull request out of it?

**Comment by germands** [comment]
I'm just kinda newbie with GIT repos and all, but I could give it a try...
