### ISSUE TITLE
Could not find com.google.android:support-v4:r13

### ISSUE THREAD

**Issue by jromero** [hayribakici/infiniteviewpager#6]
Using maven returns...

```
Could not find com.google.android:support-v4:r13.
           Required by:
           DMSKiosk:app:unspecified > com.thehayro:infiniteviewpager:0.4
```

It appears that the Android SDK repo has changed to `com.android.support:support-v4:13.0.0`

**Comment by hayribakici** [comment]
yes the repo has changed. Thank you. 
The repo is now com.android.support:support-v4:18.0.0
If your maven has trouble finding the repo you can copy the directory `$ANDROID_HOME/extras/android/m2repository/com/android/support to ~/.m2/repository/com/android`
