### ISSUE TITLE
How to auto scroll it with animation?

### ISSUE THREAD

**Issue by RyanYi8** [hayribakici/infiniteviewpager#8]
FYI . With method viewPagerInstance.setCurrentIndicator(index) , it scrolls with no animation. Can anyone help me how to achieve it ? Thanks a lot !

**Comment by hayribakici** [comment]
Hi, this feature is not set because the infiniteViewPager works a little different than the usual ViewPager. For that I need to touch the library code. How urgent do you need this feature?

cheers

**Comment by hayribakici** [comment]
won't do
